### PR TITLE
Update to pros 4

### LINKED ISSUE #1: PROS 4 Recompile

### PR DESCRIPTION
**Pull request by alexDickhans**
Updates to pros 4

closes #1

### CODE REVIEW

**Comment by liam-teale** [comment]
Has this been tested?

**Comment by alexDickhans** [comment]
Not yet, I’ll work on it this afternoon, my pros cli was up to something

**Comment by alexDickhans** [comment]
Just added a test for eigen, I'll test it in about 2 hours

**Comment by alexDickhans** [comment]
Tested and works!
```bash
m =
79.0001 65.4785 30.7382
60.5418 47.8429 72.6262
69.1491 35.7732 44.0127
m * v =
302.172
374.106
272.734
```

**Review by liam-teale — APPROVED** [review]
LGTM

**Pull request merged**
